### ISSUE TITLE
Improve "Game Over!" message readability

### ISSUE THREAD

**Issue by KiranKumarHS** [PalashBansal/Collision#22]
### Description of the Issue

Keep the message poped out for more time (eg.- 3secs) and reduce the hidden time (eg.- 1.5secs)
Also show message the moment collision happens.

### Steps to Reproduce the Issue

1.  Play game and strike to any ghost
2. wait for a while and "Game over" message appears.

### Expected Behavior

Message should appear immediately and should be there on screen for longer duration.
Also, font size and color can be changed for better readability.

### Actual Behavior

Message takes time to appear initially. Also, it resides for same time 1sec based on below code snippet-
```
	callBlink();
		}, 1000);
```

**Comment by mojiwa** [comment]
I tried to raise the PR for the fix, but it failed with an error I've not seen before: 
`[error]Resource not accessible by integration`

Sorry, I don't know how to fix that on my end.

**Comment by PalashBansal** [comment]
> I tried to raise the PR for the fix, but it failed with an error I've not seen before:
> `[error]Resource not accessible by integration`
> 
> Sorry, I don't know how to fix that on my end.

@mojiwa Thanks for your first PR, changes look fine, I will review and take action accordingly.
However, "All checks have failed" failure is because of unknown issue in https://github.com/PalashBansal/Collision/blob/master/.github/workflows/greetings.yml , error for which can be seen here- https://github.com/PalashBansal/Collision/pull/24/checks?check_run_id=1042991508

**Comment by PalashBansal** [comment]
Merged PR to 'main' but keeping issue opened coz of 2nd half issue- "Also, font size and color can be changed for better readability."

**Comment by mojiwa** [comment]
> Merged PR to 'main' but keeping issue opened coz of 2nd half issue- "Also, font size and color can be changed for better readability."

Ahh sorry. Totally missed this part. If I get a chance tomorrow, I'll try and sort this as well.
