### ISSUE TITLE
Tooltip style not correct

### ISSUE THREAD

**Issue by PalashBansal** [PalashBansal/Collision#32]
Copying on button "copy address" shows tooltip, gray background of which doesn't cover full text.
![image](https://user-images.githubusercontent.com/6822117/92216906-90dabe00-eeb4-11ea-95d6-6b3ab1211ff0.png)

Hint of fix:
<style/> section of index.htm need to be edited

**Comment by emilioCosta** [comment]
I'll get this one.

**Comment by emilioCosta** [comment]
https://github.com/PalashBansal/Collision/pull/33
