### ISSUE TITLE
Best score gone on tab reopen

### ISSUE THREAD

**Issue by PalashBansal** [PalashBansal/Collision#42]
### Description of the Issue
Best score is retained if-
reloading tab by reload button
or, pressing enter on URL
or, reopen closed tab
but not when reopening http://palashbansal.github.io/Collision/ again in fresh tab or window

### Steps to Reproduce the Issue

1. Play game and observe that score is saved.
2. Close tab and open new tab with http://palashbansal.github.io/Collision/ URL
3. Obsreve that best score is set to 0
OR,
1. Close all browser windows
2. Open browser again and go to URL- http://palashbansal.github.io/Collision/
3. Observe that best score is gone.

### Expected Behavior
Best score should always be there until user himself clears "Browsing data"

### Actual Behavior

Best score is gone too soon.

**Comment by PalashBansal** [comment]
Tester in Google chrome browser.

**Comment by PalashBansal** [comment]
@astriskit might be interested in this.

**Comment by astriskit** [comment]
The feature atm is such that - it will be kept until the tab is closed; And hence is not a bug! It is mentioned in the PR - #37 
But If this is a feature-request ;), will push a PR for the same! 

And in that case feel free to punch this issue to me and label it as enhancement @PalashBansal
