### ISSUE TITLE
Adhoc of #45- Improvement of movement keys functionality.

### ISSUE THREAD

**Issue by PalashBansal** [PalashBansal/Collision#51]
**Is your feature request related to a problem? Please describe.**

It's a standard to provide capability for user to play with keyboard itself. Functionality is there now but can be improved.

**Describe the solution you'd like**

Arrow keys support can be provided so gamer can just press up/down/left/right to move pacman. - (Already implemented in #50)

### To be done-

> Two keys simultaneously to bring diagonal movement(For eg.- top and right arrow or W+D to move to right up diagonal)

> Game starts only on left click on pacman. Game should also start by pressing any movement key.

**Comment by PalashBansal** [comment]
@albertodeago might be interested 😄

**Comment by albertodeago** [comment]
Not sure if I will be able to take this one, leaving open for other ppl for now :)

**Comment by PalashBansal** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> It's a standard to provide capability for user to play with keyboard itself. Functionality is there now but can be improved.
> 
> **Describe the solution you'd like**
> 
> Arrow keys support can be provided so gamer can just press up/down/left/right to move pacman. - (Already implemented in #50)
> 
> ### To be done-
> > Two keys simultaneously to bring diagonal movement(For eg.- top and right arrow or W+D to move to right up diagonal)
> 
> > Game starts only on left click on pacman. Game should also start by pressing any movement key.

Noticed that the following is already working-
_Two keys simultaneously to bring diagonal movement(For eg.- top and right arrow or W+D to move to right up diagonal)_

But this is not working-
Game starts in no time at the moment user clicks on pacman. While starting and continuing playing with mouse is easy, it's difficult to switch faster from game start(mouse left click) to coming to keys.
_Want: Game starts only on left click on pacman. Game should also start by pressing any movement key._
